### ISSUE TITLE
[question] When will lets-plot-skia support kotlin 2.0.0 and Compose 1.6.10?

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot-skia#11]

**Comment by alshan** [comment]
Typically Lets-plot skia does not need to be updated with each new version of Compose multiplatform as long as backward compatibility is not broken. 
Have you tried to build your app with lets-plot skia and Compose Multiplatform 1.6.10?

Kotlin 2.0 should maintain backward compatibility and support older libraries. Thus, nothing stands in your way of switching to Kotlin 2.0.

There is also a versioning info in Compose Multiplatform dos : https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-compatibility-and-versioning.html#kotlin-compatibility .

**Comment by changhexuefei** [comment]
When I updated the Kotlin version to 1.9.24 and the Compose version to 1.6.10, the following error was reported:


org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8
kotlin.code.style=official
kotlin.version=1.9.24
compose.version=1.6.10
org.gradle.warning.mode=all
exposedVersion=0.49.0

![image](https://github.com/JetBrains/lets-plot-skia/assets/19502034/ca68efe9-76fc-4ecc-b35f-55e303483b17)

**Comment by IKupriyanov-HORIS** [comment]
In [v0.8.0](https://github.com/JetBrains/skiko/releases/tag/v0.8.0) `skiko` [removed](https://github.com/JetBrains/skiko/commit/164732842ceedb0a8fc1c7a3c44c1c91273e110d#diff-a0d7f04fd675bb07dd8202625fc167600c86fb620582ea766c181c3e79b807c2) input handling support and few classes, including `SkikoView`, that we are using.  
In [v1.6.10](https://repo1.maven.org/maven2/org/jetbrains/compose/ui/ui-desktop/1.6.10/ui-desktop-1.6.10.pom) `Compose Multiplatform` started to use `skiko v0.8.4`.  

This means that for now `lets-plot-skia` can't be used with `Compose Multiplatform` `v1.6.10` and higher. We need to update skiko and adapt our code to the changes. Sadly there is a critical issue for us - https://github.com/JetBrains/skiko/issues/761. Have to check is it still a problem.

**Comment by alshan** [comment]
Please, see release notes: [v2.0.0](https://github.com/JetBrains/lets-plot-skia/releases/tag/v2.0.0).
