### ISSUE TITLE
When setting the title to Chinese, Chinese garbled characters appear。

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot-skia#14]
Hello, I set the title to Chinese and specified the Chinese font (the Chinese font is installed on the computer), but it is displayed as garbled characters. There is no problem with English.

![image](https://github.com/user-attachments/assets/357e74f3-a954-4dee-96b1-6a1254f4a7e2)

![image](https://github.com/user-attachments/assets/1c545e8d-2832-4619-aaf1-5a87189da926)

![image](https://github.com/user-attachments/assets/142b17b5-6c13-4394-91b8-bfae8f6a7527)

**Comment by alshan** [comment]
Could you try to make the "Keep ratio" text in Chinese? :
```
                        Text(
                            text = "Keep ratio:",   // <-- Use Chinese characters
                            modifier = Modifier
                                .align(CenterVertically),
                             // Your font:
                             fontFamily = FontFamily(Font("SimHei"))
                        )

```

Will it be displayed correctly?

**Comment by changhexuefei** [comment]
Hello, I modified it according to the method you gave, and it reported an error, as shown in the following figure:

![image](https://github.com/user-attachments/assets/d75be8a8-4b83-4443-91c9-88e252893125)

![image](https://github.com/user-attachments/assets/80161e0d-4058-4a13-8652-3cf7831a7b50)


![image](https://github.com/user-attachments/assets/66c1b67e-3e54-4a2b-8e6e-13d979f0e674)

**Comment by changhexuefei** [comment]
![image](https://github.com/user-attachments/assets/e35fc764-0ba2-4525-99c7-2c5697751461)

**Comment by changhexuefei** [comment]
However, when I use the built-in parameters such as fontFamily = FontFamily.Serif, or do not use the fontFamily parameter, it can display Chinese normally.

![image](https://github.com/user-attachments/assets/6817e2e2-2ed5-4f03-b502-1cf74b62964a)

**Comment by alshan** [comment]
Maybe try the font family as "宋体" (the Chinese name for SimSun)?

Anyways, you will likely want to bundle this font with your application. In this case, place `simsun.ttc` file in your resources folder and then load it in your app, e.g.:

```
val resourceFont = FontFamily(
    Font(resource = "fonts/simsun.ttf", weight = FontWeight.Normal)
)

Text(
    text = "保持比例:",
    modifier = Modifier.align(Alignment.CenterVertically),
    fontFamily = resourceFont
)

```

**Comment by changhexuefei** [comment]
Yes, putting the font resource in the resource file can make the controls in the Text display Chinese fonts correctly, but how to use it in the Letsplot control?

![image](https://github.com/user-attachments/assets/daa7aaa6-ca83-4bff-8a16-5dcb6ffd08f5)

**Comment by alshan** [comment]
Good question. Indeed, you can't use it in lets-plot.

Check what fonts are available in the app:
```
val fontNames = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().availableFontFamilyNames
```
Maybe you will see simsun font under a different name like "SimSun" or Chinese name?

If you don't see it you can try to add it to the graphic env:
```
import java.awt.GraphicsEnvironment
import java.awt.Font as AwtFont

val customFont = AwtFont.createFont(AwtFont.TRUETYPE_FONT, File(path))
GraphicsEnvironment.getLocalGraphicsEnvironment().registerFont(customFont)
```

But make sure you are using the actual name of simsun font in system.

**Comment by changhexuefei** [comment]
Hello, I typed out all the font names and used the fonts installed on the computer, but it still displays garbled characters. Is there something wrong with the method I used?

![image](https://github.com/user-attachments/assets/5f691d53-da11-430b-befa-a50329a1da8e)

![image](https://github.com/user-attachments/assets/20387c51-0ddf-4a48-b5ff-a61c34abce13)

**Comment by changhexuefei** [comment]
Hello, there is a strange phenomenon. I set the properties of plotSubTitle and axisTitle in the code, and they can display Chinese correctly, but the Chinese setting of plotTitle does not take effect. Why?

![image](https://github.com/user-attachments/assets/977ca4f4-7a3e-494f-b071-861619ca3f50)

![image](https://github.com/user-attachments/assets/5961c1b3-68f8-433d-b1c6-8d66cf6024b0)

**Comment by IKupriyanov-HORIS** [comment]
@changhexuefei Interesting! I'll investigate why this is happening.
