### ISSUE TITLE
Compose multiplatform version has been updated to 1.7.0, please add support for the above.

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot-skia#24]
Compose multiplatform version has been updated to 1.7.0, please add support for the above.

![image](https://github.com/user-attachments/assets/fd718f9d-64ad-40ad-bff9-f6198ab5bcde)

![image](https://github.com/user-attachments/assets/592d4e1e-65b6-423d-8d6d-b96061daef79)

![image](https://github.com/user-attachments/assets/3e8e4f49-4da8-416d-9148-09ad488dff75)

**Comment by changhexuefei** [comment]
Hello, regarding this issue, have you updated anything recently?

**Comment by IKupriyanov-HORIS** [comment]
Hi! We've finished the migration to Compose Multiplatform 1.7.0. A few features are still missing from Lets-Plot 4.5.1, such as ggtb() and cursor support for hyperlinks. I hope to make progress on these next week.

**Comment by changhexuefei** [comment]
Thank you very much, looking forward to it.

**Comment by changhexuefei** [comment]
Hello, after updating the version to 2.1.0-alpha1, it can run normally, but there is a warning such as Unsupported attribute `stroke-dashoffset` in Line.

**Comment by changhexuefei** [comment]
There is also a border line circled in red in the picture. Is this normal?

![image](https://github.com/user-attachments/assets/bfd52306-f5fa-418c-8900-d41ef03503e6)

**Comment by changhexuefei** [comment]
Hello, as shown in the figure, there are two curve controls, and the vertical border line in the second curve is thicker than the vertical border line in the first curve.


![image](https://github.com/user-attachments/assets/fd2cdb6b-a53e-48ce-9a32-5b00f08e5ebc)

**Comment by IKupriyanov-HORIS** [comment]
We released [v2.1.0](https://github.com/JetBrains/lets-plot-skia/releases/tag/v2.1.0) with support for Compose 1.7.0 and 1.7.1.

@changhexuefei If you still encounter rendering issues, please open a new issue.
