### ISSUE TITLE
 Does PlotPanel support dynamically refreshing data

### ISSUE THREAD

**Issue by changhexuefei** [JetBrains/lets-plot-skia#6]
Hello, does PlotPanel support dynamically refreshing data? I use a timer to refresh the data regularly. When refreshing the data, the PlotPanel flashes.

https://github.com/JetBrains/lets-plot-skia/assets/19502034/dbbc0ddc-4309-445b-bdab-165dc0eb5f67

**Comment by IKupriyanov-HORIS** [comment]
Hi! We are aware about this issue and experimenting with a fix.

**Comment by changhexuefei** [comment]
@IKupriyanov-HORIS Hello, is there any progress on this issue now?

**Comment by IKupriyanov-HORIS** [comment]
@changhexuefei Hi! Yes, we have a fix and are testing it now. It shouldn't take long.

**Comment by IKupriyanov-HORIS** [comment]
@changhexuefei We just released [v1.0.2](https://github.com/JetBrains/lets-plot-skia/releases/tag/v1.0.2) that should fix your issue. Demo can be found [here](https://github.com/JetBrains/lets-plot-compose-demos/blob/main/compose-desktop/src/main/kotlin/demo/letsPlot/composeDesktop/redraw/FastRedrawAppMain.kt). 

And here is a video how it looks:

https://github.com/JetBrains/lets-plot-skia/assets/14200189/9b9caa06-b389-4289-9ff1-c7c0b1ab29cc

**Comment by changhexuefei** [comment]
OK, thank you for your reply and fixing the issues.
